/**
 * Multilingual support for JSON Compressor
 * Add new languages by extending the translations object
 */

const translations = {
    en: {
        name: "English",
        dir: "ltr",
        translations: {
            // Header
            title: "MyJSON Tools",
            subtitle: "Because life's too short for bad JSON tools",
            
            // Modes
            modeTransform: "Transform",
            modeCompare: "Compare",
            
            // Input Panel
            inputTitle: "Source",
            inputPlaceholder: "Paste your JSON here...",
            
            // Compare Mode
            jsonA: "JSON A (Original)",
            jsonB: "JSON B (Modified)",
            jsonAPlaceholder: "Paste first JSON here...",
            jsonBPlaceholder: "Paste second JSON here...",
            clear: "Clear",
            compare: "Compare",
            swap: "Swap",
            diffOutput: "Differences",
            diffPlaceholder: "Click 'Compare' button to see differences between JSON A and JSON B",
            clearInput: "Clear",
            paste: "Paste",
            sample: "Sample",
            
            // Output Panel
            outputTitle: "Result",
            outputPlaceholder: "Output will appear here...",
            copyToInput: "Copy to Input",
            copy: "Copy",
            download: "Download",
            clearOutput: "Clear",
            
            // Control Buttons
            compress: "Compress",
            beautify: "Format",
            sort: "Sort",
            typescript: "TypeScript",
            yaml: "YAML",
            xml: "XML",
            csv: "CSV",
            queryParams: "Query Params",
            flatten: "Flatten",
            unflatten: "Unflatten",
            escape: "Escape",
            unescape: "Unescape",
            decompress: "Decompress",
            base64Encode: "Encode",
            base64Decode: "Decode",
            
            // Button Groups
            groupFormat: "Format",
            groupNested: "Nested/Flat",
            groupString: "String",
            groupConverters: "Converters",
            groupEncoding: "Encoding",
            
            // Stats
            lines: "lines",
            smaller: "smaller",
            larger: "larger",
            
            // Data Summary
            dataSummary: "Data Summary",
            strings: "strings",
            numbers: "numbers",
            booleans: "booleans",
            objects: "objects",
            arrays: "arrays",
            nulls: "nulls",
            maxDepth: "Max Depth",
            totalKeys: "Total Keys",
            
            // Validation Errors
            validationError: "Validation Error",
            errorAt: "Error at",
            line: "line",
            column: "column",
            
            // Notifications
            compressSuccess: "JSON compressed successfully",
            beautifySuccess: "JSON beautified successfully",
            sortSuccess: "JSON sorted successfully",
            typescriptSuccess: "TypeScript interfaces generated successfully",
            yamlSuccess: "JSON converted to YAML successfully",
            xmlSuccess: "JSON converted to XML successfully",
            csvSuccess: "JSON converted to CSV successfully",
            queryParamsSuccess: "JSON converted to Query Params successfully",
            queryParamsToJsonSuccess: "Query Params converted to JSON successfully",
            flattenSuccess: "JSON flattened successfully",
            unflattenSuccess: "JSON unflattened successfully",
            escapeSuccess: "String escaped successfully",
            unescapeSuccess: "String unescaped successfully",
            decompressSuccess: "JSON decompressed successfully",
            base64EncodeSuccess: "Text encoded to Base64 successfully",
            base64DecodeSuccess: "Base64 decoded successfully",
            invalidJson: "Invalid JSON",
            conversionError: "Conversion error",
            nothingToCopy: "Nothing to copy",
            copiedToClipboard: "Copied to clipboard",
            copiedToInput: "Output copied to input successfully",
            nothingToCopyToInput: "No output to copy to input",
            nothingToCompress: "Please enter some JSON to compress",
            nothingToBeautify: "Please enter some JSON to beautify",
            nothingToSort: "Please enter some JSON to sort",
            nothingToTypescript: "Please enter some JSON to generate TypeScript interfaces",
            nothingToYaml: "Please enter some JSON to convert to YAML",
            nothingToXml: "Please enter some JSON to convert to XML",
            nothingToCsv: "Please enter some JSON to convert to CSV",
            nothingToQueryParams: "Please enter some JSON or Query Params to convert",
            nothingToFlatten: "Please enter some JSON to flatten",
            nothingToUnflatten: "Please enter some JSON to unflatten",
            nothingToEscape: "Please enter some text to escape",
            nothingToUnescape: "Please enter some text to unescape",
            nothingToBase64Encode: "Please enter some text to encode",
            nothingToBase64Decode: "Please enter some Base64 text to decode",
            invalidBase64: "Invalid Base64 string",
            escapeError: "Escape error",
            unescapeError: "Unescape error",
            nothingToDecompress: "Please enter some JSON to decompress",
            pastedFromClipboard: "Pasted from clipboard",
            clipboardAccessError: "Could not access clipboard",
            nothingToDownload: "Nothing to download",
            fileDownloaded: "File downloaded",
            sampleLoaded: "Sample JSON loaded",
            
            // Footer
            footer: "Built with precision • Open Source • Privacy First",
            
            // Tooltips
            tooltipClearInput: "Clear input",
            tooltipPaste: "Paste from clipboard",
            tooltipSample: "Load sample JSON",
            tooltipImportUrl: "Import JSON from URL",
            tooltipDataSummary: "Toggle data type summary",
            tooltipCopyToInput: "Copy output to input for further processing",
            tooltipFontSize: "Change font size",
            
            // Font Size
            fontSize: "Font Size",
            fontSizeSmall: "Small",
            fontSizeMedium: "Medium",
            fontSizeLarge: "Large",
            
            // URL Import
            importFromUrl: "Import from URL",
            urlInputLabel: "Enter JSON URL:",
            urlInputPlaceholder: "https://api.example.com/data.json",
            urlInputHint: "Enter a URL that returns JSON data. CORS must be enabled on the server.",
            cancel: "Cancel",
            import: "Import",
            importing: "Importing...",
            importedFromUrl: "JSON imported successfully from URL",
            enterValidUrl: "Please enter a valid URL",
            invalidUrl: "Invalid URL format",
            importError: "Failed to import JSON from URL",
            corsError: "CORS error: The server doesn't allow cross-origin requests",
            invalidJsonResponse: "The URL didn't return valid JSON",
            httpError: "HTTP Error:",
            tooltipCopy: "Copy to clipboard",
            tooltipDownload: "Download as file",
            tooltipClearOutput: "Clear output",
            tooltipCompress: "Compress JSON",
            tooltipBeautify: "Beautify JSON",
            tooltipSort: "Sort JSON keys",
            tooltipTypescript: "Generate TypeScript interfaces",
            tooltipYaml: "Convert JSON to YAML",
            tooltipXml: "Convert JSON to XML",
            tooltipCsv: "Convert JSON to CSV",
            tooltipQueryParams: "Convert JSON to URL Query Parameters (or reverse)",
            tooltipFlatten: "Flatten nested JSON to dot notation",
            tooltipUnflatten: "Unflatten dot notation to nested JSON",
            tooltipEscape: "Escape string for JSON (add backslashes)",
            tooltipUnescape: "Unescape JSON string (remove backslashes)",
            tooltipBase64Encode: "Encode text to Base64",
            tooltipBase64Decode: "Decode Base64 to text",
            tooltipDecompress: "Decompress JSON",
            tooltipTransformMode: "Transform and convert JSON",
            tooltipCompareMode: "Compare two JSON objects",
            tooltipCompare: "Compare JSON A and JSON B",
            tooltipSwap: "Swap JSON A and JSON B",
            previousDiff: "Previous difference",
            nextDiff: "Next difference",
            toggleDetails: "Toggle details panel",
            diffDetails: "Difference Details"
        }
    },
    
    es: {
        name: "Español",
        dir: "ltr",
        translations: {
            title: "MyJSON Tools",
            subtitle: "Porque la vida es demasiado corta para malas herramientas JSON",
            
            modeTransform: "Transformar",
            modeCompare: "Comparar",
            
            inputTitle: "Fuente",
            inputPlaceholder: "Pega tu JSON aquí...",
            
            jsonA: "JSON A (Original)",
            jsonB: "JSON B (Modificado)",
            jsonAPlaceholder: "Pega el primer JSON aquí...",
            jsonBPlaceholder: "Pega el segundo JSON aquí...",
            clear: "Limpiar",
            compare: "Comparar",
            swap: "Intercambiar",
            diffOutput: "Diferencias",
            diffPlaceholder: "Haz clic en 'Comparar' para ver las diferencias entre JSON A y JSON B",
            clearInput: "Limpiar",
            paste: "Pegar",
            sample: "Ejemplo",
            
            outputTitle: "Resultado",
            outputPlaceholder: "La salida aparecerá aquí...",
            copyToInput: "Copiar a Entrada",
            copy: "Copiar",
            download: "Descargar",
            clearOutput: "Limpiar",
            
            compress: "Comprimir",
            beautify: "Formatear",
            sort: "Ordenar",
            typescript: "TypeScript",
            yaml: "YAML",
            xml: "XML",
            csv: "CSV",
            queryParams: "Parámetros de Consulta",
            flatten: "Aplanar",
            unflatten: "Desaplanar",
            escape: "Escapar",
            unescape: "Desescapar",
            decompress: "Descomprimir",
            base64Encode: "Codificar",
            base64Decode: "Decodificar",
            
            groupFormat: "Formato",
            groupNested: "Anidado/Plano",
            groupString: "Cadena",
            groupConverters: "Convertidores",
            groupEncoding: "Codificación",
            
            lines: "líneas",
            smaller: "más pequeño",
            larger: "más grande",
            
            dataSummary: "Resumen de Datos",
            strings: "cadenas",
            numbers: "números",
            booleans: "booleanos",
            objects: "objetos",
            arrays: "arreglos",
            nulls: "nulos",
            maxDepth: "Profundidad Máx",
            totalKeys: "Total de Claves",
            
            validationError: "Error de Validación",
            errorAt: "Error en",
            line: "línea",
            column: "columna",
            
            compressSuccess: "JSON comprimido exitosamente",
            beautifySuccess: "JSON embellecido exitosamente",
            sortSuccess: "JSON ordenado exitosamente",
            typescriptSuccess: "Interfaces de TypeScript generadas exitosamente",
            yamlSuccess: "JSON convertido a YAML exitosamente",
            xmlSuccess: "JSON convertido a XML exitosamente",
            csvSuccess: "JSON convertido a CSV exitosamente",
            queryParamsSuccess: "JSON convertido a Parámetros de Consulta exitosamente",
            queryParamsToJsonSuccess: "Parámetros de Consulta convertidos a JSON exitosamente",
            flattenSuccess: "JSON aplanado exitosamente",
            unflattenSuccess: "JSON desaplanado exitosamente",
            escapeSuccess: "Cadena escapada exitosamente",
            unescapeSuccess: "Cadena desescapada exitosamente",
            decompressSuccess: "JSON descomprimido exitosamente",
            base64EncodeSuccess: "Texto codificado a Base64 exitosamente",
            base64DecodeSuccess: "Base64 decodificado exitosamente",
            invalidJson: "JSON inválido",
            conversionError: "Error de conversión",
            nothingToCopy: "Nada que copiar",
            copiedToClipboard: "Copiado al portapapeles",
            copiedToInput: "Salida copiada a entrada exitosamente",
            nothingToCopyToInput: "No hay salida para copiar a entrada",
            nothingToCompress: "Por favor ingresa un JSON para comprimir",
            nothingToBeautify: "Por favor ingresa un JSON para embellecer",
            nothingToSort: "Por favor ingresa un JSON para ordenar",
            nothingToTypescript: "Por favor ingresa un JSON para generar interfaces de TypeScript",
            nothingToYaml: "Por favor ingresa un JSON para convertir a YAML",
            nothingToXml: "Por favor ingresa un JSON para convertir a XML",
            nothingToCsv: "Por favor ingresa un JSON para convertir a CSV",
            nothingToQueryParams: "Por favor ingresa un JSON o Parámetros de Consulta para convertir",
            nothingToFlatten: "Por favor ingresa un JSON para aplanar",
            nothingToUnflatten: "Por favor ingresa un JSON para desaplanar",
            nothingToEscape: "Por favor ingresa texto para escapar",
            nothingToUnescape: "Por favor ingresa texto para desescapar",
            nothingToBase64Encode: "Por favor ingresa texto para codificar",
            nothingToBase64Decode: "Por favor ingresa texto Base64 para decodificar",
            invalidBase64: "Cadena Base64 inválida",
            escapeError: "Error al escapar",
            unescapeError: "Error al desescapar",
            nothingToDecompress: "Por favor ingresa un JSON para descomprimir",
            pastedFromClipboard: "Pegado desde el portapapeles",
            clipboardAccessError: "No se pudo acceder al portapapeles",
            nothingToDownload: "Nada que descargar",
            fileDownloaded: "Archivo descargado",
            sampleLoaded: "JSON de ejemplo cargado",
            
            footer: "Construido con precisión • Código Abierto • Privacidad Primero",
            
            tooltipClearInput: "Limpiar entrada",
            tooltipPaste: "Pegar desde portapapeles",
            tooltipSample: "Cargar JSON de ejemplo",
            tooltipImportUrl: "Importar JSON desde URL",
            tooltipDataSummary: "Alternar resumen de tipos de datos",
            tooltipCopyToInput: "Copiar salida a entrada para procesamiento adicional",
            tooltipFontSize: "Cambiar tamaño de fuente",
            
            // Font Size
            fontSize: "Tamaño de Fuente",
            fontSizeSmall: "Pequeño",
            fontSizeMedium: "Mediano",
            fontSizeLarge: "Grande",
            
            // URL Import
            importFromUrl: "Importar desde URL",
            urlInputLabel: "Ingrese la URL del JSON:",
            urlInputPlaceholder: "https://api.ejemplo.com/datos.json",
            urlInputHint: "Ingrese una URL que devuelva datos JSON. CORS debe estar habilitado en el servidor.",
            cancel: "Cancelar",
            import: "Importar",
            importing: "Importando...",
            importedFromUrl: "JSON importado exitosamente desde URL",
            enterValidUrl: "Por favor ingrese una URL válida",
            invalidUrl: "Formato de URL inválido",
            importError: "Error al importar JSON desde URL",
            corsError: "Error CORS: El servidor no permite solicitudes de origen cruzado",
            invalidJsonResponse: "La URL no devolvió JSON válido",
            httpError: "Error HTTP:",
            tooltipCopy: "Copiar al portapapeles",
            tooltipDownload: "Descargar como archivo",
            tooltipClearOutput: "Limpiar salida",
            tooltipCompress: "Comprimir JSON",
            tooltipBeautify: "Embellecer JSON",
            tooltipSort: "Ordenar claves JSON",
            tooltipTypescript: "Generar interfaces de TypeScript",
            tooltipYaml: "Convertir JSON a YAML",
            tooltipXml: "Convertir JSON a XML",
            tooltipCsv: "Convertir JSON a CSV",
            tooltipQueryParams: "Convertir JSON a Parámetros de Consulta URL (o viceversa)",
            tooltipFlatten: "Aplanar JSON anidado a notación de puntos",
            tooltipUnflatten: "Desaplanar notación de puntos a JSON anidado",
            tooltipEscape: "Escapar cadena para JSON (agregar barras invertidas)",
            tooltipUnescape: "Desescapar cadena JSON (eliminar barras invertidas)",
            tooltipBase64Encode: "Codificar texto a Base64",
            tooltipBase64Decode: "Decodificar Base64 a texto",
            tooltipDecompress: "Descomprimir JSON",
            tooltipTransformMode: "Transformar y convertir JSON",
            tooltipCompareMode: "Comparar dos objetos JSON",
            tooltipCompare: "Comparar JSON A y JSON B",
            tooltipSwap: "Intercambiar JSON A y JSON B",
            previousDiff: "Diferencia anterior",
            nextDiff: "Siguiente diferencia",
            toggleDetails: "Alternar panel de detalles",
            diffDetails: "Detalles de las Diferencias"
        }
    },
    
    ar: {
        name: "العربية",
        dir: "rtl",
        translations: {
            title: "MyJSON Tools",
            subtitle: "لأن الحياة أقصر من أن تضيعها في أدوات JSON سيئة",
            
            modeTransform: "تحويل",
            modeCompare: "مقارنة",
            
            inputTitle: "المصدر",
            inputPlaceholder: "الصق JSON هنا...",
            
            jsonA: "JSON A (الأصلي)",
            jsonB: "JSON B (المعدّل)",
            jsonAPlaceholder: "الصق JSON الأول هنا...",
            jsonBPlaceholder: "الصق JSON الثاني هنا...",
            clear: "مسح",
            compare: "مقارنة",
            swap: "تبديل",
            diffOutput: "الاختلافات",
            diffPlaceholder: "انقر على زر 'مقارنة' لرؤية الاختلافات بين JSON A و JSON B",
            clearInput: "مسح",
            paste: "لصق",
            sample: "مثال",
            
            outputTitle: "النتيجة",
            outputPlaceholder: "سيظهر الإخراج هنا...",
            copyToInput: "نسخ إلى الإدخال",
            copy: "نسخ",
            download: "تحميل",
            clearOutput: "مسح",
            
            compress: "ضغط",
            beautify: "تنسيق",
            sort: "ترتيب",
            typescript: "TypeScript",
            yaml: "YAML",
            xml: "XML",
            csv: "CSV",
            queryParams: "معاملات الاستعلام",
            flatten: "تسطيح",
            unflatten: "إلغاء التسطيح",
            escape: "الهروب",
            unescape: "إلغاء الهروب",
            decompress: "فك الضغط",
            base64Encode: "ترميز",
            base64Decode: "فك الترميز",
            
            groupFormat: "التنسيق",
            groupNested: "متداخل/مسطح",
            groupString: "سلسلة",
            groupConverters: "محولات",
            groupEncoding: "الترميز",
            
            lines: "أسطر",
            smaller: "أصغر",
            larger: "أكبر",
            
            dataSummary: "ملخص البيانات",
            strings: "نصوص",
            numbers: "أرقام",
            booleans: "منطقية",
            objects: "كائنات",
            arrays: "مصفوفات",
            nulls: "فارغة",
            maxDepth: "أقصى عمق",
            totalKeys: "إجمالي المفاتيح",
            
            validationError: "خطأ في التحقق",
            errorAt: "خطأ في",
            line: "السطر",
            column: "العمود",
            
            compressSuccess: "تم ضغط JSON بنجاح",
            beautifySuccess: "تم تجميل JSON بنجاح",
            sortSuccess: "تم ترتيب JSON بنجاح",
            typescriptSuccess: "تم إنشاء واجهات TypeScript بنجاح",
            yamlSuccess: "تم تحويل JSON إلى YAML بنجاح",
            xmlSuccess: "تم تحويل JSON إلى XML بنجاح",
            csvSuccess: "تم تحويل JSON إلى CSV بنجاح",
            queryParamsSuccess: "تم تحويل JSON إلى معاملات الاستعلام بنجاح",
            queryParamsToJsonSuccess: "تم تحويل معاملات الاستعلام إلى JSON بنجاح",
            flattenSuccess: "تم تسطيح JSON بنجاح",
            unflattenSuccess: "تم إلغاء تسطيح JSON بنجاح",
            escapeSuccess: "تم الهروب من السلسلة بنجاح",
            unescapeSuccess: "تم إلغاء الهروب من السلسلة بنجاح",
            decompressSuccess: "تم فك ضغط JSON بنجاح",
            base64EncodeSuccess: "تم ترميز النص إلى Base64 بنجاح",
            base64DecodeSuccess: "تم فك ترميز Base64 بنجاح",
            invalidJson: "JSON غير صالح",
            conversionError: "خطأ في التحويل",
            nothingToCopy: "لا يوجد شيء للنسخ",
            copiedToClipboard: "تم النسخ إلى الحافظة",
            copiedToInput: "تم نسخ الإخراج إلى الإدخال بنجاح",
            nothingToCopyToInput: "لا يوجد إخراج لنسخه إلى الإدخال",
            nothingToCompress: "الرجاء إدخال JSON للضغط",
            nothingToBeautify: "الرجاء إدخال JSON للتجميل",
            nothingToSort: "الرجاء إدخال JSON للترتيب",
            nothingToTypescript: "الرجاء إدخال JSON لإنشاء واجهات TypeScript",
            nothingToYaml: "الرجاء إدخال JSON للتحويل إلى YAML",
            nothingToXml: "الرجاء إدخال JSON للتحويل إلى XML",
            nothingToCsv: "الرجاء إدخال JSON للتحويل إلى CSV",
            nothingToQueryParams: "الرجاء إدخال JSON أو معاملات الاستعلام للتحويل",
            nothingToFlatten: "الرجاء إدخال JSON للتسطيح",
            nothingToUnflatten: "الرجاء إدخال JSON لإلغاء التسطيح",
            nothingToEscape: "الرجاء إدخال نص للهروب",
            nothingToUnescape: "الرجاء إدخال نص لإلغاء الهروب",
            nothingToBase64Encode: "الرجاء إدخال نص للترميز",
            nothingToBase64Decode: "الرجاء إدخال نص Base64 لفك الترميز",
            invalidBase64: "نص Base64 غير صالح",
            escapeError: "خطأ في الهروب",
            unescapeError: "خطأ في إلغاء الهروب",
            nothingToDecompress: "الرجاء إدخال JSON لفك الضغط",
            pastedFromClipboard: "تم اللصق من الحافظة",
            clipboardAccessError: "تعذر الوصول إلى الحافظة",
            nothingToDownload: "لا يوجد شيء للتحميل",
            fileDownloaded: "تم تحميل الملف",
            sampleLoaded: "تم تحميل مثال JSON",
            
            footer: "بُني بدقة • مفتوح المصدر • الخصوصية أولاً",
            
            tooltipClearInput: "مسح الإدخال",
            tooltipPaste: "لصق من الحافظة",
            tooltipSample: "تحميل مثال JSON",
            tooltipImportUrl: "استيراد JSON من URL",
            tooltipDataSummary: "تبديل ملخص أنواع البيانات",
            tooltipCopyToInput: "نسخ الإخراج إلى الإدخال لمزيد من المعالجة",
            tooltipFontSize: "تغيير حجم الخط",
            
            // Font Size
            fontSize: "حجم الخط",
            fontSizeSmall: "صغير",
            fontSizeMedium: "متوسط",
            fontSizeLarge: "كبير",
            
            // URL Import
            importFromUrl: "استيراد من URL",
            urlInputLabel: "أدخل رابط JSON:",
            urlInputPlaceholder: "https://api.example.com/data.json",
            urlInputHint: "أدخل رابطاً يُرجع بيانات JSON. يجب تفعيل CORS على الخادم.",
            cancel: "إلغاء",
            import: "استيراد",
            importing: "جاري الاستيراد...",
            importedFromUrl: "تم استيراد JSON بنجاح من URL",
            enterValidUrl: "الرجاء إدخال رابط صالح",
            invalidUrl: "تنسيق URL غير صالح",
            importError: "فشل استيراد JSON من URL",
            corsError: "خطأ CORS: الخادم لا يسمح بطلبات من مصادر مختلفة",
            invalidJsonResponse: "الرابط لم يُرجع JSON صالح",
            httpError: "خطأ HTTP:",
            tooltipCopy: "نسخ إلى الحافظة",
            tooltipDownload: "تحميل كملف",
            tooltipClearOutput: "مسح الإخراج",
            tooltipCompress: "ضغط JSON",
            tooltipBeautify: "تجميل JSON",
            tooltipSort: "ترتيب مفاتيح JSON",
            tooltipTypescript: "إنشاء واجهات TypeScript",
            tooltipYaml: "تحويل JSON إلى YAML",
            tooltipXml: "تحويل JSON إلى XML",
            tooltipCsv: "تحويل JSON إلى CSV",
            tooltipQueryParams: "تحويل JSON إلى معاملات استعلام URL (أو العكس)",
            tooltipFlatten: "تسطيح JSON المتداخل إلى تدوين النقاط",
            tooltipUnflatten: "إلغاء تسطيح تدوين النقاط إلى JSON متداخل",
            tooltipEscape: "الهروب من السلسلة لـ JSON (إضافة الشرطات المائلة العكسية)",
            tooltipUnescape: "إلغاء الهروب من سلسلة JSON (إزالة الشرطات المائلة العكسية)",
            tooltipBase64Encode: "ترميز النص إلى Base64",
            tooltipBase64Decode: "فك ترميز Base64 إلى نص",
            tooltipDecompress: "فك ضغط JSON",
            tooltipTransformMode: "تحويل وتغيير JSON",
            tooltipCompareMode: "مقارنة كائنين JSON",
            tooltipCompare: "مقارنة JSON A و JSON B",
            tooltipSwap: "تبديل JSON A و JSON B",
            previousDiff: "الاختلاف السابق",
            nextDiff: "الاختلاف التالي",
            toggleDetails: "تبديل لوحة التفاصيل",
            diffDetails: "تفاصيل الاختلافات"
        }
    },
    
    fr: {
        name: "Français",
        dir: "ltr",
        translations: {
            title: "MyJSON Tools",
            subtitle: "Parce que la vie est trop courte pour de mauvais outils JSON",
            
            modeTransform: "Transformer",
            modeCompare: "Comparer",
            
            inputTitle: "Source",
            inputPlaceholder: "Collez votre JSON ici...",
            
            jsonA: "JSON A (Original)",
            jsonB: "JSON B (Modifié)",
            jsonAPlaceholder: "Collez le premier JSON ici...",
            jsonBPlaceholder: "Collez le deuxième JSON ici...",
            clear: "Effacer",
            compare: "Comparer",
            swap: "Échanger",
            diffOutput: "Différences",
            diffPlaceholder: "Cliquez sur 'Comparer' pour voir les différences entre JSON A et JSON B",
            clearInput: "Effacer",
            paste: "Coller",
            sample: "Exemple",
            
            outputTitle: "Résultat",
            outputPlaceholder: "La sortie apparaîtra ici...",
            copyToInput: "Copier vers l'Entrée",
            copy: "Copier",
            download: "Télécharger",
            clearOutput: "Effacer",
            
            compress: "Compresser",
            beautify: "Formater",
            sort: "Trier",
            typescript: "TypeScript",
            yaml: "YAML",
            xml: "XML",
            csv: "CSV",
            queryParams: "Paramètres de Requête",
            flatten: "Aplatir",
            unflatten: "Déaplatir",
            escape: "Échapper",
            unescape: "Déséchapper",
            decompress: "Décompresser",
            base64Encode: "Encoder",
            base64Decode: "Décoder",
            
            groupFormat: "Format",
            groupNested: "Imbriqué/Plat",
            groupString: "Chaîne",
            groupConverters: "Convertisseurs",
            groupEncoding: "Encodage",
            
            lines: "lignes",
            smaller: "plus petit",
            larger: "plus grand",
            
            dataSummary: "Résumé des Données",
            strings: "chaînes",
            numbers: "nombres",
            booleans: "booléens",
            objects: "objets",
            arrays: "tableaux",
            nulls: "nuls",
            maxDepth: "Profondeur Max",
            totalKeys: "Total des Clés",
            
            validationError: "Erreur de Validation",
            errorAt: "Erreur à",
            line: "ligne",
            column: "colonne",
            
            compressSuccess: "JSON compressé avec succès",
            beautifySuccess: "JSON embelli avec succès",
            sortSuccess: "JSON trié avec succès",
            typescriptSuccess: "Interfaces TypeScript générées avec succès",
            yamlSuccess: "JSON converti en YAML avec succès",
            xmlSuccess: "JSON converti en XML avec succès",
            csvSuccess: "JSON converti en CSV avec succès",
            queryParamsSuccess: "JSON converti en Paramètres de Requête avec succès",
            queryParamsToJsonSuccess: "Paramètres de Requête convertis en JSON avec succès",
            flattenSuccess: "JSON aplati avec succès",
            unflattenSuccess: "JSON déaplati avec succès",
            escapeSuccess: "Chaîne échappée avec succès",
            unescapeSuccess: "Chaîne déséchappée avec succès",
            decompressSuccess: "JSON décompressé avec succès",
            base64EncodeSuccess: "Texte encodé en Base64 avec succès",
            base64DecodeSuccess: "Base64 décodé avec succès",
            invalidJson: "JSON invalide",
            conversionError: "Erreur de conversion",
            nothingToCopy: "Rien à copier",
            copiedToClipboard: "Copié dans le presse-papiers",
            copiedToInput: "Sortie copiée vers l'entrée avec succès",
            nothingToCopyToInput: "Aucune sortie à copier vers l'entrée",
            nothingToCompress: "Veuillez entrer un JSON à compresser",
            nothingToBeautify: "Veuillez entrer un JSON à embellir",
            nothingToSort: "Veuillez entrer un JSON à trier",
            nothingToTypescript: "Veuillez entrer un JSON pour générer des interfaces TypeScript",
            nothingToYaml: "Veuillez entrer un JSON à convertir en YAML",
            nothingToXml: "Veuillez entrer un JSON à convertir en XML",
            nothingToCsv: "Veuillez entrer un JSON à convertir en CSV",
            nothingToQueryParams: "Veuillez entrer un JSON ou des Paramètres de Requête à convertir",
            nothingToFlatten: "Veuillez entrer un JSON à aplatir",
            nothingToUnflatten: "Veuillez entrer un JSON à déaplatir",
            nothingToEscape: "Veuillez entrer du texte à échapper",
            nothingToUnescape: "Veuillez entrer du texte à déséchapper",
            nothingToBase64Encode: "Veuillez entrer du texte à encoder",
            nothingToBase64Decode: "Veuillez entrer du texte Base64 à décoder",
            invalidBase64: "Chaîne Base64 invalide",
            escapeError: "Erreur d'échappement",
            unescapeError: "Erreur de déséchappement",
            nothingToDecompress: "Veuillez entrer un JSON à décompresser",
            pastedFromClipboard: "Collé depuis le presse-papiers",
            clipboardAccessError: "Impossible d'accéder au presse-papiers",
            nothingToDownload: "Rien à télécharger",
            fileDownloaded: "Fichier téléchargé",
            sampleLoaded: "Exemple JSON chargé",
            
            footer: "Construit avec précision • Open Source • Confidentialité d'abord",
            
            tooltipClearInput: "Effacer l'entrée",
            tooltipPaste: "Coller depuis le presse-papiers",
            tooltipSample: "Charger un exemple JSON",
            tooltipImportUrl: "Importer JSON depuis URL",
            tooltipDataSummary: "Basculer le résumé des types de données",
            tooltipCopyToInput: "Copier la sortie vers l'entrée pour un traitement supplémentaire",
            tooltipFontSize: "Changer la taille de police",
            
            // Font Size
            fontSize: "Taille de Police",
            fontSizeSmall: "Petite",
            fontSizeMedium: "Moyenne",
            fontSizeLarge: "Grande",
            
            // URL Import
            importFromUrl: "Importer depuis URL",
            urlInputLabel: "Entrez l'URL JSON:",
            urlInputPlaceholder: "https://api.exemple.com/donnees.json",
            urlInputHint: "Entrez une URL qui renvoie des données JSON. CORS doit être activé sur le serveur.",
            cancel: "Annuler",
            import: "Importer",
            importing: "Importation...",
            importedFromUrl: "JSON importé avec succès depuis l'URL",
            enterValidUrl: "Veuillez entrer une URL valide",
            invalidUrl: "Format d'URL invalide",
            importError: "Échec de l'importation JSON depuis l'URL",
            corsError: "Erreur CORS: Le serveur n'autorise pas les requêtes cross-origin",
            invalidJsonResponse: "L'URL n'a pas renvoyé de JSON valide",
            httpError: "Erreur HTTP:",
            tooltipCopy: "Copier dans le presse-papiers",
            tooltipDownload: "Télécharger comme fichier",
            tooltipClearOutput: "Effacer la sortie",
            tooltipCompress: "Compresser JSON",
            tooltipBeautify: "Embellir JSON",
            tooltipSort: "Trier les clés JSON",
            tooltipTypescript: "Générer des interfaces TypeScript",
            tooltipYaml: "Convertir JSON en YAML",
            tooltipXml: "Convertir JSON en XML",
            tooltipCsv: "Convertir JSON en CSV",
            tooltipQueryParams: "Convertir JSON en Paramètres de Requête URL (ou vice versa)",
            tooltipFlatten: "Aplatir JSON imbriqué en notation pointée",
            tooltipUnflatten: "Déaplatir notation pointée en JSON imbriqué",
            tooltipEscape: "Échapper la chaîne pour JSON (ajouter des barres obliques inverses)",
            tooltipUnescape: "Déséchapper la chaîne JSON (supprimer les barres obliques inverses)",
            tooltipBase64Encode: "Encoder le texte en Base64",
            tooltipBase64Decode: "Décoder Base64 en texte",
            tooltipDecompress: "Décompresser JSON",
            tooltipTransformMode: "Transformer et convertir JSON",
            tooltipCompareMode: "Comparer deux objets JSON",
            tooltipCompare: "Comparer JSON A et JSON B",
            tooltipSwap: "Échanger JSON A et JSON B",
            previousDiff: "Différence précédente",
            nextDiff: "Prochaine différence",
            toggleDetails: "Basculer le panneau de détails",
            diffDetails: "Détails des Différences"
        }
    },
    
    de: {
        name: "Deutsch",
        dir: "ltr",
        translations: {
            title: "MyJSON Tools",
            subtitle: "Weil das Leben zu kurz für schlechte JSON-Tools ist",
            
            modeTransform: "Transformieren",
            modeCompare: "Vergleichen",
            
            inputTitle: "Quelle",
            inputPlaceholder: "JSON hier einfügen...",
            
            jsonA: "JSON A (Original)",
            jsonB: "JSON B (Geändert)",
            jsonAPlaceholder: "Erstes JSON hier einfügen...",
            jsonBPlaceholder: "Zweites JSON hier einfügen...",
            clear: "Löschen",
            compare: "Vergleichen",
            swap: "Tauschen",
            diffOutput: "Unterschiede",
            diffPlaceholder: "Klicken Sie auf 'Vergleichen', um die Unterschiede zwischen JSON A und JSON B zu sehen",
            clearInput: "Löschen",
            paste: "Einfügen",
            sample: "Beispiel",
            
            outputTitle: "Ergebnis",
            outputPlaceholder: "Die Ausgabe erscheint hier...",
            copyToInput: "Zur Eingabe Kopieren",
            copy: "Kopieren",
            download: "Herunterladen",
            clearOutput: "Löschen",
            
            compress: "Komprimieren",
            beautify: "Formatieren",
            sort: "Sortieren",
            typescript: "TypeScript",
            yaml: "YAML",
            xml: "XML",
            csv: "CSV",
            queryParams: "Abfrageparameter",
            flatten: "Abflachen",
            unflatten: "Entfalten",
            escape: "Escapieren",
            unescape: "Deescapieren",
            decompress: "Dekomprimieren",
            base64Encode: "Kodieren",
            base64Decode: "Dekodieren",
            
            groupFormat: "Format",
            groupNested: "Verschachtelt/Flach",
            groupString: "Zeichenfolge",
            groupConverters: "Konverter",
            groupEncoding: "Kodierung",
            
            lines: "Zeilen",
            smaller: "kleiner",
            larger: "größer",
            
            dataSummary: "Datenzusammenfassung",
            strings: "Zeichenketten",
            numbers: "Zahlen",
            booleans: "Boolesche Werte",
            objects: "Objekte",
            arrays: "Arrays",
            nulls: "Nullwerte",
            maxDepth: "Max. Tiefe",
            totalKeys: "Gesamtschlüssel",
            
            validationError: "Validierungsfehler",
            errorAt: "Fehler bei",
            line: "Zeile",
            column: "Spalte",
            
            compressSuccess: "JSON erfolgreich komprimiert",
            beautifySuccess: "JSON erfolgreich verschönert",
            sortSuccess: "JSON erfolgreich sortiert",
            typescriptSuccess: "TypeScript-Interfaces erfolgreich generiert",
            yamlSuccess: "JSON erfolgreich in YAML konvertiert",
            xmlSuccess: "JSON erfolgreich in XML konvertiert",
            csvSuccess: "JSON erfolgreich in CSV konvertiert",
            queryParamsSuccess: "JSON erfolgreich in Abfrageparameter konvertiert",
            queryParamsToJsonSuccess: "Abfrageparameter erfolgreich in JSON konvertiert",
            flattenSuccess: "JSON erfolgreich abgeflacht",
            unflattenSuccess: "JSON erfolgreich entfaltet",
            escapeSuccess: "Zeichenfolge erfolgreich escapiert",
            unescapeSuccess: "Zeichenfolge erfolgreich deescapiert",
            decompressSuccess: "JSON erfolgreich dekomprimiert",
            base64EncodeSuccess: "Text erfolgreich in Base64 kodiert",
            base64DecodeSuccess: "Base64 erfolgreich dekodiert",
            invalidJson: "Ungültiges JSON",
            conversionError: "Konvertierungsfehler",
            nothingToCopy: "Nichts zu kopieren",
            copiedToClipboard: "In Zwischenablage kopiert",
            copiedToInput: "Ausgabe erfolgreich zur Eingabe kopiert",
            nothingToCopyToInput: "Keine Ausgabe zum Kopieren zur Eingabe",
            nothingToCompress: "Bitte geben Sie JSON zum Komprimieren ein",
            nothingToBeautify: "Bitte geben Sie JSON zum Verschönern ein",
            nothingToSort: "Bitte geben Sie JSON zum Sortieren ein",
            nothingToTypescript: "Bitte geben Sie JSON zum Generieren von TypeScript-Interfaces ein",
            nothingToYaml: "Bitte geben Sie JSON zum Konvertieren in YAML ein",
            nothingToXml: "Bitte geben Sie JSON zum Konvertieren in XML ein",
            nothingToCsv: "Bitte geben Sie JSON zum Konvertieren in CSV ein",
            nothingToQueryParams: "Bitte geben Sie JSON oder Abfrageparameter zur Konvertierung ein",
            nothingToFlatten: "Bitte geben Sie JSON zum Abflachen ein",
            nothingToUnflatten: "Bitte geben Sie JSON zum Entfalten ein",
            nothingToEscape: "Bitte geben Sie Text zum Escapieren ein",
            nothingToUnescape: "Bitte geben Sie Text zum Deescapieren ein",
            nothingToBase64Encode: "Bitte geben Sie Text zum Kodieren ein",
            nothingToBase64Decode: "Bitte geben Sie Base64-Text zum Dekodieren ein",
            invalidBase64: "Ungültige Base64-Zeichenfolge",
            escapeError: "Escape-Fehler",
            unescapeError: "Unescape-Fehler",
            nothingToDecompress: "Bitte geben Sie JSON zum Dekomprimieren ein",
            pastedFromClipboard: "Aus Zwischenablage eingefügt",
            clipboardAccessError: "Zugriff auf Zwischenablage nicht möglich",
            nothingToDownload: "Nichts zum Herunterladen",
            fileDownloaded: "Datei heruntergeladen",
            sampleLoaded: "Beispiel-JSON geladen",
            
            footer: "Mit Präzision gebaut • Open Source • Datenschutz zuerst",
            
            tooltipClearInput: "Eingabe löschen",
            tooltipPaste: "Aus Zwischenablage einfügen",
            tooltipSample: "Beispiel-JSON laden",
            tooltipImportUrl: "JSON von URL importieren",
            tooltipDataSummary: "Datentypzusammenfassung umschalten",
            tooltipCopyToInput: "Ausgabe zur Eingabe kopieren für weitere Verarbeitung",
            tooltipFontSize: "Schriftgröße ändern",
            
            // Font Size
            fontSize: "Schriftgröße",
            fontSizeSmall: "Klein",
            fontSizeMedium: "Mittel",
            fontSizeLarge: "Groß",
            
            // URL Import
            importFromUrl: "Von URL importieren",
            urlInputLabel: "JSON-URL eingeben:",
            urlInputPlaceholder: "https://api.beispiel.com/daten.json",
            urlInputHint: "Geben Sie eine URL ein, die JSON-Daten zurückgibt. CORS muss auf dem Server aktiviert sein.",
            cancel: "Abbrechen",
            import: "Importieren",
            importing: "Importieren...",
            importedFromUrl: "JSON erfolgreich von URL importiert",
            enterValidUrl: "Bitte geben Sie eine gültige URL ein",
            invalidUrl: "Ungültiges URL-Format",
            importError: "JSON-Import von URL fehlgeschlagen",
            corsError: "CORS-Fehler: Der Server erlaubt keine Cross-Origin-Anfragen",
            invalidJsonResponse: "Die URL hat kein gültiges JSON zurückgegeben",
            httpError: "HTTP-Fehler:",
            tooltipCopy: "In Zwischenablage kopieren",
            tooltipDownload: "Als Datei herunterladen",
            tooltipClearOutput: "Ausgabe löschen",
            tooltipCompress: "JSON komprimieren",
            tooltipBeautify: "JSON verschönern",
            tooltipSort: "JSON-Schlüssel sortieren",
            tooltipTypescript: "TypeScript-Interfaces generieren",
            tooltipYaml: "JSON in YAML konvertieren",
            tooltipXml: "JSON in XML konvertieren",
            tooltipCsv: "JSON in CSV konvertieren",
            tooltipQueryParams: "JSON in URL-Abfrageparameter konvertieren (oder umgekehrt)",
            tooltipFlatten: "Verschachteltes JSON in Punktnotation abflachen",
            tooltipUnflatten: "Punktnotation in verschachteltes JSON entfalten",
            tooltipEscape: "Zeichenfolge für JSON escapieren (Backslashes hinzufügen)",
            tooltipUnescape: "JSON-Zeichenfolge deescapieren (Backslashes entfernen)",
            tooltipBase64Encode: "Text in Base64 kodieren",
            tooltipBase64Decode: "Base64 in Text dekodieren",
            tooltipDecompress: "JSON dekomprimieren",
            tooltipTransformMode: "JSON transformieren und konvertieren",
            tooltipCompareMode: "Zwei JSON-Objekte vergleichen",
            tooltipCompare: "JSON A und JSON B vergleichen",
            tooltipSwap: "JSON A und JSON B tauschen",
            previousDiff: "Vorheriger Unterschied",
            nextDiff: "Nächster Unterschied",
            toggleDetails: "Detailbereich umschalten",
            diffDetails: "Unterschiedsdetails"
        }
    }
};

// Export for use in app.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = translations;
}

