/**
 * Multilingual support for JSON Compressor
 * Add new languages by extending the translations object
 */

const translations = {
    en: {
        name: "English",
        dir: "ltr",
        translations: {
            // Header
            title: "JSON Playground",
            subtitle: "Transform, format, and convert JSON with ease",
            
            // Modes
            modeTransform: "Transform",
            modeCompare: "Compare",
            
            // Input Panel
            inputTitle: "Input JSON",
            inputPlaceholder: "Paste your JSON here...",
            
            // Compare Mode
            jsonA: "JSON A (Original)",
            jsonB: "JSON B (Modified)",
            jsonAPlaceholder: "Paste first JSON here...",
            jsonBPlaceholder: "Paste second JSON here...",
            clear: "Clear",
            compare: "Compare",
            swap: "Swap",
            diffOutput: "Differences",
            diffPlaceholder: "Click 'Compare' button to see differences between JSON A and JSON B",
            clearInput: "Clear",
            paste: "Paste",
            sample: "Sample",
            
            // Output Panel
            outputTitle: "Output JSON",
            outputPlaceholder: "Output will appear here...",
            copy: "Copy",
            download: "Download",
            clearOutput: "Clear",
            
            // Control Buttons
            compress: "Compress",
            beautify: "Beautify",
            sort: "Sort",
            typescript: "TypeScript",
            yaml: "YAML",
            xml: "XML",
            decompress: "Decompress",
            
            // Stats
            lines: "lines",
            smaller: "smaller",
            larger: "larger",
            
            // Notifications
            compressSuccess: "JSON compressed successfully",
            beautifySuccess: "JSON beautified successfully",
            sortSuccess: "JSON sorted successfully",
            typescriptSuccess: "TypeScript interfaces generated successfully",
            yamlSuccess: "JSON converted to YAML successfully",
            xmlSuccess: "JSON converted to XML successfully",
            decompressSuccess: "JSON decompressed successfully",
            invalidJson: "Invalid JSON",
            nothingToCopy: "Nothing to copy",
            copiedToClipboard: "Copied to clipboard",
            nothingToCompress: "Please enter some JSON to compress",
            nothingToBeautify: "Please enter some JSON to beautify",
            nothingToSort: "Please enter some JSON to sort",
            nothingToTypescript: "Please enter some JSON to generate TypeScript interfaces",
            nothingToYaml: "Please enter some JSON to convert to YAML",
            nothingToXml: "Please enter some JSON to convert to XML",
            nothingToDecompress: "Please enter some JSON to decompress",
            pastedFromClipboard: "Pasted from clipboard",
            clipboardAccessError: "Could not access clipboard",
            nothingToDownload: "Nothing to download",
            fileDownloaded: "File downloaded",
            sampleLoaded: "Sample JSON loaded",
            
            // Footer
            footer: "Built with precision • Following golden ratio principles",
            
            // Tooltips
            tooltipClearInput: "Clear input",
            tooltipPaste: "Paste from clipboard",
            tooltipSample: "Load sample JSON",
            tooltipCopy: "Copy to clipboard",
            tooltipDownload: "Download as file",
            tooltipClearOutput: "Clear output",
            tooltipCompress: "Compress JSON",
            tooltipBeautify: "Beautify JSON",
            tooltipSort: "Sort JSON keys",
            tooltipTypescript: "Generate TypeScript interfaces",
            tooltipYaml: "Convert JSON to YAML",
            tooltipXml: "Convert JSON to XML",
            tooltipDecompress: "Decompress JSON",
            tooltipTransformMode: "Transform and convert JSON",
            tooltipCompareMode: "Compare two JSON objects",
            tooltipCompare: "Compare JSON A and JSON B",
            tooltipSwap: "Swap JSON A and JSON B",
            previousDiff: "Previous difference",
            nextDiff: "Next difference",
            toggleDetails: "Toggle details panel",
            diffDetails: "Difference Details"
        }
    },
    
    es: {
        name: "Español",
        dir: "ltr",
        translations: {
            title: "JSON Playground",
            subtitle: "Transforma, formatea y convierte JSON con facilidad",
            
            modeTransform: "Transformar",
            modeCompare: "Comparar",
            
            inputTitle: "JSON de Entrada",
            inputPlaceholder: "Pega tu JSON aquí...",
            
            jsonA: "JSON A (Original)",
            jsonB: "JSON B (Modificado)",
            jsonAPlaceholder: "Pega el primer JSON aquí...",
            jsonBPlaceholder: "Pega el segundo JSON aquí...",
            clear: "Limpiar",
            compare: "Comparar",
            swap: "Intercambiar",
            diffOutput: "Diferencias",
            diffPlaceholder: "Haz clic en 'Comparar' para ver las diferencias entre JSON A y JSON B",
            clearInput: "Limpiar",
            paste: "Pegar",
            sample: "Ejemplo",
            
            outputTitle: "JSON de Salida",
            outputPlaceholder: "La salida aparecerá aquí...",
            copy: "Copiar",
            download: "Descargar",
            clearOutput: "Limpiar",
            
            compress: "Comprimir",
            beautify: "Embellecer",
            sort: "Ordenar",
            typescript: "TypeScript",
            yaml: "YAML",
            xml: "XML",
            decompress: "Descomprimir",
            
            lines: "líneas",
            smaller: "más pequeño",
            larger: "más grande",
            
            compressSuccess: "JSON comprimido exitosamente",
            beautifySuccess: "JSON embellecido exitosamente",
            sortSuccess: "JSON ordenado exitosamente",
            typescriptSuccess: "Interfaces de TypeScript generadas exitosamente",
            yamlSuccess: "JSON convertido a YAML exitosamente",
            xmlSuccess: "JSON convertido a XML exitosamente",
            decompressSuccess: "JSON descomprimido exitosamente",
            invalidJson: "JSON inválido",
            nothingToCopy: "Nada que copiar",
            copiedToClipboard: "Copiado al portapapeles",
            nothingToCompress: "Por favor ingresa un JSON para comprimir",
            nothingToBeautify: "Por favor ingresa un JSON para embellecer",
            nothingToSort: "Por favor ingresa un JSON para ordenar",
            nothingToTypescript: "Por favor ingresa un JSON para generar interfaces de TypeScript",
            nothingToYaml: "Por favor ingresa un JSON para convertir a YAML",
            nothingToXml: "Por favor ingresa un JSON para convertir a XML",
            nothingToDecompress: "Por favor ingresa un JSON para descomprimir",
            pastedFromClipboard: "Pegado desde el portapapeles",
            clipboardAccessError: "No se pudo acceder al portapapeles",
            nothingToDownload: "Nada que descargar",
            fileDownloaded: "Archivo descargado",
            sampleLoaded: "JSON de ejemplo cargado",
            
            footer: "Construido con precisión • Siguiendo principios de proporción áurea",
            
            tooltipClearInput: "Limpiar entrada",
            tooltipPaste: "Pegar desde portapapeles",
            tooltipSample: "Cargar JSON de ejemplo",
            tooltipCopy: "Copiar al portapapeles",
            tooltipDownload: "Descargar como archivo",
            tooltipClearOutput: "Limpiar salida",
            tooltipCompress: "Comprimir JSON",
            tooltipBeautify: "Embellecer JSON",
            tooltipSort: "Ordenar claves JSON",
            tooltipTypescript: "Generar interfaces de TypeScript",
            tooltipYaml: "Convertir JSON a YAML",
            tooltipXml: "Convertir JSON a XML",
            tooltipDecompress: "Descomprimir JSON",
            tooltipTransformMode: "Transformar y convertir JSON",
            tooltipCompareMode: "Comparar dos objetos JSON",
            tooltipCompare: "Comparar JSON A y JSON B",
            tooltipSwap: "Intercambiar JSON A y JSON B",
            previousDiff: "Diferencia anterior",
            nextDiff: "Siguiente diferencia",
            toggleDetails: "Alternar panel de detalles",
            diffDetails: "Detalles de las Diferencias"
        }
    },
    
    ar: {
        name: "العربية",
        dir: "rtl",
        translations: {
            title: "JSON Playground",
            subtitle: "حوّل، نسّق، وغيّر JSON بسهولة",
            
            modeTransform: "تحويل",
            modeCompare: "مقارنة",
            
            inputTitle: "JSON الإدخال",
            inputPlaceholder: "الصق JSON هنا...",
            
            jsonA: "JSON A (الأصلي)",
            jsonB: "JSON B (المعدّل)",
            jsonAPlaceholder: "الصق JSON الأول هنا...",
            jsonBPlaceholder: "الصق JSON الثاني هنا...",
            clear: "مسح",
            compare: "مقارنة",
            swap: "تبديل",
            diffOutput: "الاختلافات",
            diffPlaceholder: "انقر على زر 'مقارنة' لرؤية الاختلافات بين JSON A و JSON B",
            clearInput: "مسح",
            paste: "لصق",
            sample: "مثال",
            
            outputTitle: "JSON الإخراج",
            outputPlaceholder: "سيظهر الإخراج هنا...",
            copy: "نسخ",
            download: "تحميل",
            clearOutput: "مسح",
            
            compress: "ضغط",
            beautify: "تجميل",
            sort: "ترتيب",
            typescript: "TypeScript",
            yaml: "YAML",
            xml: "XML",
            decompress: "فك الضغط",
            
            lines: "أسطر",
            smaller: "أصغر",
            larger: "أكبر",
            
            compressSuccess: "تم ضغط JSON بنجاح",
            beautifySuccess: "تم تجميل JSON بنجاح",
            sortSuccess: "تم ترتيب JSON بنجاح",
            typescriptSuccess: "تم إنشاء واجهات TypeScript بنجاح",
            yamlSuccess: "تم تحويل JSON إلى YAML بنجاح",
            xmlSuccess: "تم تحويل JSON إلى XML بنجاح",
            decompressSuccess: "تم فك ضغط JSON بنجاح",
            invalidJson: "JSON غير صالح",
            nothingToCopy: "لا يوجد شيء للنسخ",
            copiedToClipboard: "تم النسخ إلى الحافظة",
            nothingToCompress: "الرجاء إدخال JSON للضغط",
            nothingToBeautify: "الرجاء إدخال JSON للتجميل",
            nothingToSort: "الرجاء إدخال JSON للترتيب",
            nothingToTypescript: "الرجاء إدخال JSON لإنشاء واجهات TypeScript",
            nothingToYaml: "الرجاء إدخال JSON للتحويل إلى YAML",
            nothingToXml: "الرجاء إدخال JSON للتحويل إلى XML",
            nothingToDecompress: "الرجاء إدخال JSON لفك الضغط",
            pastedFromClipboard: "تم اللصق من الحافظة",
            clipboardAccessError: "تعذر الوصول إلى الحافظة",
            nothingToDownload: "لا يوجد شيء للتحميل",
            fileDownloaded: "تم تحميل الملف",
            sampleLoaded: "تم تحميل مثال JSON",
            
            footer: "بُني بدقة • باتباع مبادئ النسبة الذهبية",
            
            tooltipClearInput: "مسح الإدخال",
            tooltipPaste: "لصق من الحافظة",
            tooltipSample: "تحميل مثال JSON",
            tooltipCopy: "نسخ إلى الحافظة",
            tooltipDownload: "تحميل كملف",
            tooltipClearOutput: "مسح الإخراج",
            tooltipCompress: "ضغط JSON",
            tooltipBeautify: "تجميل JSON",
            tooltipSort: "ترتيب مفاتيح JSON",
            tooltipTypescript: "إنشاء واجهات TypeScript",
            tooltipYaml: "تحويل JSON إلى YAML",
            tooltipXml: "تحويل JSON إلى XML",
            tooltipDecompress: "فك ضغط JSON",
            tooltipTransformMode: "تحويل وتغيير JSON",
            tooltipCompareMode: "مقارنة كائنين JSON",
            tooltipCompare: "مقارنة JSON A و JSON B",
            tooltipSwap: "تبديل JSON A و JSON B",
            previousDiff: "الاختلاف السابق",
            nextDiff: "الاختلاف التالي",
            toggleDetails: "تبديل لوحة التفاصيل",
            diffDetails: "تفاصيل الاختلافات"
        }
    },
    
    fr: {
        name: "Français",
        dir: "ltr",
        translations: {
            title: "JSON Playground",
            subtitle: "Transformez, formatez et convertissez JSON facilement",
            
            modeTransform: "Transformer",
            modeCompare: "Comparer",
            
            inputTitle: "JSON d'Entrée",
            inputPlaceholder: "Collez votre JSON ici...",
            
            jsonA: "JSON A (Original)",
            jsonB: "JSON B (Modifié)",
            jsonAPlaceholder: "Collez le premier JSON ici...",
            jsonBPlaceholder: "Collez le deuxième JSON ici...",
            clear: "Effacer",
            compare: "Comparer",
            swap: "Échanger",
            diffOutput: "Différences",
            diffPlaceholder: "Cliquez sur 'Comparer' pour voir les différences entre JSON A et JSON B",
            clearInput: "Effacer",
            paste: "Coller",
            sample: "Exemple",
            
            outputTitle: "JSON de Sortie",
            outputPlaceholder: "La sortie apparaîtra ici...",
            copy: "Copier",
            download: "Télécharger",
            clearOutput: "Effacer",
            
            compress: "Compresser",
            beautify: "Embellir",
            sort: "Trier",
            typescript: "TypeScript",
            yaml: "YAML",
            xml: "XML",
            decompress: "Décompresser",
            
            lines: "lignes",
            smaller: "plus petit",
            larger: "plus grand",
            
            compressSuccess: "JSON compressé avec succès",
            beautifySuccess: "JSON embelli avec succès",
            sortSuccess: "JSON trié avec succès",
            typescriptSuccess: "Interfaces TypeScript générées avec succès",
            yamlSuccess: "JSON converti en YAML avec succès",
            xmlSuccess: "JSON converti en XML avec succès",
            decompressSuccess: "JSON décompressé avec succès",
            invalidJson: "JSON invalide",
            nothingToCopy: "Rien à copier",
            copiedToClipboard: "Copié dans le presse-papiers",
            nothingToCompress: "Veuillez entrer un JSON à compresser",
            nothingToBeautify: "Veuillez entrer un JSON à embellir",
            nothingToSort: "Veuillez entrer un JSON à trier",
            nothingToTypescript: "Veuillez entrer un JSON pour générer des interfaces TypeScript",
            nothingToYaml: "Veuillez entrer un JSON à convertir en YAML",
            nothingToXml: "Veuillez entrer un JSON à convertir en XML",
            nothingToDecompress: "Veuillez entrer un JSON à décompresser",
            pastedFromClipboard: "Collé depuis le presse-papiers",
            clipboardAccessError: "Impossible d'accéder au presse-papiers",
            nothingToDownload: "Rien à télécharger",
            fileDownloaded: "Fichier téléchargé",
            sampleLoaded: "Exemple JSON chargé",
            
            footer: "Construit avec précision • Suivant les principes du nombre d'or",
            
            tooltipClearInput: "Effacer l'entrée",
            tooltipPaste: "Coller depuis le presse-papiers",
            tooltipSample: "Charger un exemple JSON",
            tooltipCopy: "Copier dans le presse-papiers",
            tooltipDownload: "Télécharger comme fichier",
            tooltipClearOutput: "Effacer la sortie",
            tooltipCompress: "Compresser JSON",
            tooltipBeautify: "Embellir JSON",
            tooltipSort: "Trier les clés JSON",
            tooltipTypescript: "Générer des interfaces TypeScript",
            tooltipYaml: "Convertir JSON en YAML",
            tooltipXml: "Convertir JSON en XML",
            tooltipDecompress: "Décompresser JSON",
            tooltipTransformMode: "Transformer et convertir JSON",
            tooltipCompareMode: "Comparer deux objets JSON",
            tooltipCompare: "Comparer JSON A et JSON B",
            tooltipSwap: "Échanger JSON A et JSON B",
            previousDiff: "Différence précédente",
            nextDiff: "Prochaine différence",
            toggleDetails: "Basculer le panneau de détails",
            diffDetails: "Détails des Différences"
        }
    },
    
    de: {
        name: "Deutsch",
        dir: "ltr",
        translations: {
            title: "JSON Playground",
            subtitle: "JSON einfach transformieren, formatieren und konvertieren",
            
            modeTransform: "Transformieren",
            modeCompare: "Vergleichen",
            
            inputTitle: "Eingabe-JSON",
            inputPlaceholder: "JSON hier einfügen...",
            
            jsonA: "JSON A (Original)",
            jsonB: "JSON B (Geändert)",
            jsonAPlaceholder: "Erstes JSON hier einfügen...",
            jsonBPlaceholder: "Zweites JSON hier einfügen...",
            clear: "Löschen",
            compare: "Vergleichen",
            swap: "Tauschen",
            diffOutput: "Unterschiede",
            diffPlaceholder: "Klicken Sie auf 'Vergleichen', um die Unterschiede zwischen JSON A und JSON B zu sehen",
            clearInput: "Löschen",
            paste: "Einfügen",
            sample: "Beispiel",
            
            outputTitle: "Ausgabe-JSON",
            outputPlaceholder: "Die Ausgabe erscheint hier...",
            copy: "Kopieren",
            download: "Herunterladen",
            clearOutput: "Löschen",
            
            compress: "Komprimieren",
            beautify: "Verschönern",
            sort: "Sortieren",
            typescript: "TypeScript",
            yaml: "YAML",
            xml: "XML",
            decompress: "Dekomprimieren",
            
            lines: "Zeilen",
            smaller: "kleiner",
            larger: "größer",
            
            compressSuccess: "JSON erfolgreich komprimiert",
            beautifySuccess: "JSON erfolgreich verschönert",
            sortSuccess: "JSON erfolgreich sortiert",
            typescriptSuccess: "TypeScript-Interfaces erfolgreich generiert",
            yamlSuccess: "JSON erfolgreich in YAML konvertiert",
            xmlSuccess: "JSON erfolgreich in XML konvertiert",
            decompressSuccess: "JSON erfolgreich dekomprimiert",
            invalidJson: "Ungültiges JSON",
            nothingToCopy: "Nichts zu kopieren",
            copiedToClipboard: "In Zwischenablage kopiert",
            nothingToCompress: "Bitte geben Sie JSON zum Komprimieren ein",
            nothingToBeautify: "Bitte geben Sie JSON zum Verschönern ein",
            nothingToSort: "Bitte geben Sie JSON zum Sortieren ein",
            nothingToTypescript: "Bitte geben Sie JSON zum Generieren von TypeScript-Interfaces ein",
            nothingToYaml: "Bitte geben Sie JSON zum Konvertieren in YAML ein",
            nothingToXml: "Bitte geben Sie JSON zum Konvertieren in XML ein",
            nothingToDecompress: "Bitte geben Sie JSON zum Dekomprimieren ein",
            pastedFromClipboard: "Aus Zwischenablage eingefügt",
            clipboardAccessError: "Zugriff auf Zwischenablage nicht möglich",
            nothingToDownload: "Nichts zum Herunterladen",
            fileDownloaded: "Datei heruntergeladen",
            sampleLoaded: "Beispiel-JSON geladen",
            
            footer: "Mit Präzision gebaut • Nach dem Goldenen Schnitt",
            
            tooltipClearInput: "Eingabe löschen",
            tooltipPaste: "Aus Zwischenablage einfügen",
            tooltipSample: "Beispiel-JSON laden",
            tooltipCopy: "In Zwischenablage kopieren",
            tooltipDownload: "Als Datei herunterladen",
            tooltipClearOutput: "Ausgabe löschen",
            tooltipCompress: "JSON komprimieren",
            tooltipBeautify: "JSON verschönern",
            tooltipSort: "JSON-Schlüssel sortieren",
            tooltipTypescript: "TypeScript-Interfaces generieren",
            tooltipYaml: "JSON in YAML konvertieren",
            tooltipXml: "JSON in XML konvertieren",
            tooltipDecompress: "JSON dekomprimieren",
            tooltipTransformMode: "JSON transformieren und konvertieren",
            tooltipCompareMode: "Zwei JSON-Objekte vergleichen",
            tooltipCompare: "JSON A und JSON B vergleichen",
            tooltipSwap: "JSON A und JSON B tauschen",
            previousDiff: "Vorheriger Unterschied",
            nextDiff: "Nächster Unterschied",
            toggleDetails: "Detailbereich umschalten",
            diffDetails: "Unterschiedsdetails"
        }
    }
};

// Export for use in app.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = translations;
}

